name: Release

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Pack
        run: .\build.ps1 -Target Pack --TagName="$GITHUB_REF" --Commit="$GITHUB_SHA"
        shell: pwsh
      
      - name: Publish
        run: dotnet nuget push packages-build/*.nupkg -k {{ secrets.NUGET_APIKEY }}
        shell: cmd
      
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: NuGet Packages
          path: packages-build
