name: Unpublish

on: 
  release:
    types: [unpublished,deleted]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Get Version
        id: version
        run: .\build.ps1 -Target OutputVersion --TagName="${env:GITHUB_REF}" --Commit="${env:GITHUB_SHA}"
        shell: pwsh
      
      - name: Unpublish
        run: dotnet nuget delete BuildInformationParser {{ steps.version.outputs.SEMANTIC_VERSION }} -s https://api.nuget.org/v3/index.json -k {{ secrets.NUGET_APIKEY }} --non-interactive
        shell: cmd